services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespg
      - POSTGRES_DB=apiFiles
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  localstack:
      image: localstack/localstack
      container_name: localstack
      ports:
        - "4566:4566"
      environment:
        - SERVICES=s3
        - DEFAULT_REGION=us-east-1
        - DATA_DIR=/tmp/localstack/data
        - DEBUG=1
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./localstack_data:/var/lib/localstack"

volumes:
  postgres_data: